language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: Sg7DjnqZCRMWpC/kRkh0eXP6C5GCQcm4q/tu4l5ywWa81ecKW4y1yMjMYbtYzAA8yFgaUpdS0XyZDzjEIZx2ywse4jJu6HFHyWu9097hPEum6KIi1Pi/Kp5CGEytzhaMDJfY5i2P/rn6lgOhCr9Ub9chNx1biX93T9QLquT+awHfTBnxs6FjHPgl9uhah/HbYNwHmXfXt26r5neWnR8G0uvi+iGTbRGYhZbSfGvbpkDAajqUvGhnK8WmJub3o7RyMOJPDfdwYLx0oNkoHQHkd9YwqXV+fIZ+oUnIbrkWZnQRwuJUtoKaQmVqPrtbp93qrwhSO6T7Bm5WVE2MmHvrLYbqLGntCsMIWxUBAqg/c1V07WnA5mRADiE9FqFZQLldja2sc7B+55Hx8VR/Yva3tb3WHhi8Ahgx+aWWIQBBpSu+j/2qKciKRXhUB/1/TX0xM+1hsFhZXc+Kpxg18ApecEGbu2qwggU5Uvvz0hm5RcuMQjzMeTZ9w8YLnWEWS62wsMDJvEuu3mGHOm+AQEr8GQKg4pYK6SAx2N5n7ubMttW02QLPUpY/mKUI4gtEf/G7DEb7dzIHWBaOEYu/7WiOM/BTRrw7KK14pEaFHpol2rEM48hyRu4zx0Nex7v68uCHBcDSHVmh8NtiI9SKlzBRyLMENbExRTWHV1h6pEWphek=
  app:
    master: chswomenintech
    staging: stagingchswit
  on:
    repo: Women-In-Tech-CHS/wit
before_script:
- psql -c 'create database wtech_test;' -U postgres
install:
- bundle install --jobs=3 --retry=3
