language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: A00mItJXl50h/T8hQJ/HlyGQTakjB4HdC0lm9QTxpOC+wbmrJpjrJ6AnWTDHVV188KuuhVwaSrDpC1c5tjMs8vPax63uFsJwHbwmYfYrqqzGddItJpj6MZBOtZUtZ5RZR4+YwCOoEO9c/OPQ7bUwtHx14SGYY2zBoQP4VZhPhm9fKUAFIz0Aqz76M3CGzpLxb93l0BvnQHGYuSWuct+8q5eLiKrpDfp0UQap/ya25wO2fLELgbemoXnR9uthDyc6Riyfgt0gGE9BvqM3MZDJgR+ZU8bMfLUxI2ZiGs2w9W+eSxqkWlVl+Koi80en5Jk4lx4q2BRuucXuyWc/vvjRHmSefKTN1RXIr4AMZrKsP8pAh35qtKql0W6OLWQQnwwQpZ2ArW+L0u2FORuDz0S49TO1BYAHr0GWqnXH1+/kpiuLhGZkhs0Y85C1HBrCqFRZaP+EDBeFRtHvDeC1h0T1Z1dbysvOBMASdzgGRMQOwl40YWU31mSvg3zFvNPARk2MYFLzj7FYJBhtnrz2yygNQCgebakkq30RENgGlnYtKMO81NfLTaftfzoVdOxpU3D/lmvTysDYnZEc5GAze4dN0bXHPAfMsHYX+I5BkPU1LiDXXCw66gIqLiZ3qCwIJ3n7hlc7kPJBDiHPBQgo6KXQLq9tpp2FJNwNUCuzXqD7G9Q=
  app: chswomenintech
  on:
    repo: easmith2/wit
before_script:
- psql -c 'create database wtech_test;' -U postgres
install:
- bundle install --jobs=3 --retry=3
