language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: ZnaV05NDp0iPqhV5UhwmVuMuX7dhPMTNViKQxpIxXKGd9521A1nq6H9SzYQBBJJyCSbKGxvlp4uQ/TWxkkWRZHfujCZ1HpsDdBbnoBdkSEWQowjJAtlY5KvwAqfY6m6WSr38vIDgFHzTVwO3UQKbkn2PGoHEmsd8Rgg4IoCij0vJ5pqKYyrccw7E8NXuGCzO0nU5SAFVxoTaDDLRnPi2BJkvGZ+i7LG2BN+b1oB66rhy46Ot26g/bc+sXHF7K+H4WInrWCGFbWAn1pOb02EEWs/wdXbRvhoxoGqouwoeTNpWnCmpG1+SHjgNDj5vVU6BNoeO0rkXMpIG8a9EuDiP9Mj1wnKmGO5gFgXycVVDHeAQKn5dLw/Pwz8CfSLe3D5uC29O/SZHQHHgy1Bva6s2s9rSO9KjBUOzlzqMBqIhIzjL+/xrG9VR9YFeK+YVbgGYvwUKrfYhSZhTab4rUwEA1j/5asFPyT2MfP5Slcakrn3v39zrl3PWGG3vP6L12kLGDAC0RQRn3wbN+IOe81Jd5wnRf4snRrriWCo5kRCxdMCtWR79ZDN7Mvvf6xKpItK5hVUN/8D3mET9VD2yl2zPA7zrA5GOq1IKkrCqtoiF7WxNVB1vUDaW5d5r1TWv2pNp8e6Iag4VawSOav3pYU4wGgkhrjJmbrn6fNRaGQdrrdw=
  app: chswomenintech
  on:
    repo: easmith2/wit
before_script:
- psql -c 'create database wtech_test;' -U postgres
install:
- bundle install --jobs=3 --retry=3
